
server:
  port: 8081
services:
  urls:
    service1: http://localhost:8080
    service2: http://localhost:8081
  methods:
    service1:
      - method1
      - method2
    service2:
      - method3
      - method4