services:
  service1: http://example.com/service1
  service2: http://example.com/service2

serviceMethods:
  service1:
    - getUserByUserId
    - insertUserId
  service2:
    - getUserName
    - insertUserName