config:
  center:
    url: http://localhost:8080
spring:
  main:
    allow-circular-references: true
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: utf-8
    cache: false
    template-loader-path: classpath:/templates/freemarker/
    check-template-location: true
  mail:
    host: smtp.test.com
    username: userId

userId:
  header: userId

dispose:
  advice-filter-package:
    - springfox.documentation
    - org.springframework
easyjob:
  node:
    strategy: weight # Node task fetching strategy, default, id_hash, least_count, weight, others depend on heartbeat switch
    fetchPeriod: 100  # Node task fetching period, in milliseconds
    fetchDuration: 300 # Duration for which node fetches tasks that are about to execute, in seconds
  pool:
    queueSize: 1000 # Queue capacity of the node's task execution thread pool
    coreSize: 5 # Initial thread count of the node's task execution thread pool
    maxSize: 10 # Maximum thread count of the node's task execution thread pool
  heartBeat:
    enable: true # Whether to enable heartbeat, only when enabled do the strategies other than default become effective, and the exception recovery thread below becomes valid
    seconds: 10  # Node heartbeat period, in seconds, reports to the database every few seconds that it is still alive
  recover:
    enable: true # Whether to enable the node's exception state recovery thread, depends on the heartbeat switch
    seconds: 30  # How often, in seconds, the node's exception state recovery thread processes unfinished tasks of disconnected nodes, depends on the heartbeat switch

server:
  port: 8081
services:
  urls:
    service1: http://localhost:8080
    service2: http://localhost:8081
